// all the products

var PRODUCTS = [
  { id: 1,  name: "Baby Spinach",       cat: "Vegetables", farm: "Fortuin Farm",    loc: "Ceres, WC",        price: 18,  orig: 22,   unit: "bunch", img: "images/babyspinach.jpg",  season: ["Mar","Apr","May","Jun","Jul","Aug","Sep","Oct"],                           desc: "Freshly harvested baby spinach. No pesticides. Best refrigerated, consume within 5 days.",                          farmer: "Johannes Fortuin",  farmerEst: "2001" },
  { id: 2,  name: "Butternut Squash",   cat: "Vegetables", farm: "Kleinplaas",      loc: "Paarl, WC",        price: 22,  orig: null, unit: "kg",    img: "images/butternut.jpeg",   season: ["Mar","Apr","May","Jun","Jul","Aug"],                                       desc: "Sweet, dense butternut grown in the fertile Paarl valley. Perfect for soups and roasting.",                       farmer: "Rina Engelbrecht",  farmerEst: "1998" },
  { id: 3,  name: "Roma Tomatoes",      cat: "Vegetables", farm: "Fortuin Farm",    loc: "Ceres, WC",        price: 30,  orig: 35,   unit: "kg",    img: "images/tomatoes.jpg",     season: ["Nov","Dec","Jan","Feb","Mar"],                                             desc: "Firm, flavourful roma tomatoes. Sun-ripened and harvested at peak freshness.",                                   farmer: "Johannes Fortuin",  farmerEst: "2001" },
  { id: 4,  name: "Kale",               cat: "Vegetables", farm: "Greenvlei Farm",  loc: "Stellenbosch, WC", price: 24,  orig: null, unit: "bunch", img: "images/kale.jpg",         season: ["Apr","May","Jun","Jul","Aug","Sep"],                                       desc: "Curly kale, rich in nutrients. Great for salads, smoothies, and stir-fries.",                                   farmer: "Sipho Ndlovu",      farmerEst: "2015" },
  { id: 5,  name: "Amadumbe",           cat: "Vegetables", farm: "Ubuntu Growers",  loc: "KZN",              price: 28,  orig: null, unit: "kg",    img: "images/amadumbe.jpg",     season: ["Feb","Mar","Apr","May"],                                                  desc: "Traditional South African taro root. Nutritious, earthy, and versatile in cooking.",                            farmer: "Bongani Dlamini",   farmerEst: "2010" },
  { id: 6,  name: "Sweet Potato",       cat: "Vegetables", farm: "Kleinplaas",      loc: "Paarl, WC",        price: 19,  orig: null, unit: "kg",    img: "images/sweetpotato.jpg",  season: ["Mar","Apr","May","Jun"],                                                  desc: "Orange-fleshed sweet potatoes, naturally sweet and high in vitamin A.",                                         farmer: "Rina Engelbrecht",  farmerEst: "1998" },
  { id: 7,  name: "Pink Lady Apples",   cat: "Fruits",     farm: "Valley Orchards", loc: "Elgin, WC",        price: 45,  orig: 55,   unit: "kg",    img: "images/apples.jpg",       season: ["Feb","Mar","Apr","May"],                                                  desc: "Crisp, sweet-tart apples from the Elgin valley. Perfect for snacking and baking.",                              farmer: "Pieter van Wyk",    farmerEst: "1990" },
  { id: 8,  name: "Sorghum Flour",      cat: "Grains",     farm: "Ubuntu Growers",  loc: "KZN",              price: 60,  orig: null, unit: "500g",  img: "images/sorghum.jpg",      season: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],   desc: "Stone-ground sorghum flour. A traditional SA grain, gluten-free and high in fibre.",                            farmer: "Bongani Dlamini",   farmerEst: "2010" },
  { id: 9,  name: "Harvest Box",        cat: "Boxes",      farm: "Mzansi Roots",    loc: "Western Cape",     price: 250, orig: 320,  unit: "box",   img: "images/harvestbox.jpg",   season: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],   desc: "A curated seasonal box from 3-4 farms. Includes 6-8 items selected at peak freshness. Subscribe and save 20%.", farmer: "Various farms",     farmerEst: "-"   },
];